Adminsitrador.Usuarios.Web/Pages/Users/Action.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Adminsitrador.Usuarios.Web.Data;
using Adminsitrador.Usuarios.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Adminsitrador.Usuarios.Web.Pages.Users
{
    public class ActionModel : PageModel
    {
        private readonly UsersRepository usersRepository;
        private readonly ProfilesRepository profilesRepository;
        private readonly DocumentTypesRepository documentTypesRepository;

        [BindProperty]
        public UserRequest User { get; set; }
        public List<Profile> Profiles { get; set; }
        public List<DocumentType> DocumentTypes { get; set; }
        public long? Id { get; set; }
        public string Message { get; set; }

        public ActionModel(UsersRepository usersRepository, ProfilesRepository profilesRepository, DocumentTypesRepository documentTypesRepository)
        {
            this.usersRepository = usersRepository;
            this.profilesRepository = profilesRepository;
            this.documentTypesRepository = documentTypesRepository;
        }

        public void OnGet(long? id)
        {
            Id = id;
            Init(id);
        }

        public void OnPostNew()
        {
            try
            {
                var userRequest = new UserRequest()
                {
                    Active = User.Active,
                    CreateBy = 1111111111,
                    DateCreate = DateTime.Now,
                    DateModify = null,
                    DocumentNumber = User.DocumentNumber,
                    DocumentType_id = User.DocumentType_id,
                    Email = $"{User.Name}@{User.Surname}",
                    Login = User.Login,
                    ModifyBy = null,
                    Name = User.Name,
                    Password = User.Password,
                    Profile_Id = User.Profile_Id,
                    Surname = User.Surname
                };
                var idResponse = usersRepository.PostUsersInsert(userRequest);
                if (idResponse == 0)
                    Message = $"Error al insertar el registro, valide los campos";
                else
                    Message = $"Se inserto correctamente el id {idResponse}";
            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }
            Init(null);
        }

        public void OnPostUpdate()
        {
            try
            {
                var userRequest = new UserRequest()
                {
                    Id = User.Id,
                    Active = User.Active,
                    CreateBy = User.CreateBy,
                    DateCreate = User.DateCreate,
                    DateModify = DateTime.Now,
                    DocumentNumber = User.DocumentNumber,
                    DocumentType_id = User.DocumentType_id,
                    Email = User.Email,
                    Login = User.Login,
                    ModifyBy = 1111111111,
                    Name = User.Name,
                    Password = User.Password,
                    Profile_Id = User.Profile_Id,
                    Surname = User.Surname
                };
                var response = usersRepository.PostUsersUpdate(userRequest);
                if (response)
                    Message = $"El registro se actualizo correctamente";
                else
                    Message = $"Error al actualizar el registro";
            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }
            Init(User.Id);
        }

        private void Init(long? id)
        {
            Profiles = profilesRepository.GetProfiles();
            DocumentTypes = documentTypesRepository.GetDocumentTypes();

            if (id != null)
            {
                User = usersRepository.GetUsers(id.Value);
            }
        }
    }
}

Adminsitrador.Usuarios.Web/Pages/Users/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Adminsitrador.Usuarios.Web.Data;
using Adminsitrador.Usuarios.Web.Models;
using Adminsitrador.Usuarios.Web.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Adminsitrador.Usuarios.Web.Pages.Users
{
    public class IndexModel : PageModel
    {
        private readonly UsersRepository usersRepository;
        private readonly ProfilesRepository profilesRepository;
        private readonly DocumentTypesRepository documentTypesRepository;
        public List<UserResponse> Users { get; set; }
        public List<Profile> Profiles { get; set; }
        public List<DocumentType> DocumentTypes { get; set; }

        public IndexModel(UsersRepository usersRepository, ProfilesRepository profilesRepository, DocumentTypesRepository documentTypesRepository)
        {
            this.usersRepository = usersRepository;
            this.profilesRepository = profilesRepository;
            this.documentTypesRepository = documentTypesRepository;
        }

        public void OnGet()
        {
            try
            {
                var userRequests = usersRepository.GetUsers();
                Profiles = profilesRepository.GetProfiles();
                DocumentTypes = documentTypesRepository.GetDocumentTypes();

                Users = MapUser.MapUserResponse(userRequests, Profiles, DocumentTypes);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Adminsitrador.Usuarios.Web/Pages/Users/Action.cshtml
@page "{id:int?}"
@model Adminsitrador.Usuarios.Web.Pages.Users.ActionModel
@{
    Layout = null;
    ViewData["Title"] = "Admi de Usuarios";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admi de Usuarios</title>
    <link href="~/css/action.css" rel="stylesheet" />
    <link href="~/css/users.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="page-container">
        <div class="titulo-container">
            <h3>Creación o modificación de usuarios</h3>
        </div>
        @if (Model.Id == null)
        {
            <form method="post">
                <div class="form-container">
                    <div class="item-form-container">
                        <label>Tipo Documento</label>
                        <select asp-items="@(new SelectList(Model.DocumentTypes,"Id","_DocumentType"))" asp-for="@Model.User.DocumentType_id" class="select">
                            <option value="" selected disabled>--Seleccione--</option>
                        </select>
                        <span asp-validation-for="@Model.User.DocumentType_id"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Nro de documento</label>
                        <input asp-for="@Model.User.DocumentNumber" placeholder="Nro de documento" />
                        <span asp-validation-for="@Model.User.DocumentNumber"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Nombre</label>
                        <input asp-for="@Model.User.Name" placeholder="Nombre" />
                        <span asp-validation-for="@Model.User.Name"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Apellido</label>
                        <input asp-for="@Model.User.Surname" placeholder="Apellido" />
                        <span asp-validation-for="@Model.User.Surname"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Login</label>
                        <input asp-for="@Model.User.Login" placeholder="Login" />
                        <span asp-validation-for="@Model.User.Login"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Password</label>
                        <input asp-for="@Model.User.Password" placeholder="Password" type="password" />
                        <span asp-validation-for="@Model.User.Password"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Perfil</label>
                        <select asp-items="@(new SelectList(Model.Profiles,"Id","_Profile"))" asp-for="@Model.User.Profile_Id" class="select">
                            <option value="" selected disabled>--Seleccione--</option>
                        </select>
                        <span asp-validation-for="@Model.User.Profile_Id"></span>
                    </div>
                    <div class="item-form-container check">
                        <input asp-for="@Model.User.Active" type="checkbox" style="width: 10%;" />
                        <label style="margin: 0;">Activo</label>
                    </div>
                </div>
                <div class="titulo-container"></div>
                <div class="button-container">
                    <div class="button-group-container">
                        <a href="/Users">
                            <div class="button"><span>Volver</span></div>
                        </a>
                        <input class="button" type="submit" value="Guardar" asp-page-handler="New" />
                    </div>
                </div>
            </form>
        }
        else
        {
            <form method="post">
                <div class="form-container">
                    <input type="hidden" asp-for="@Model.User.Id" />
                    <input type="hidden" asp-for="@Model.User.CreateBy" />
                    <input type="hidden" asp-for="@Model.User.DateCreate" />
                    <input type="hidden" asp-for="@Model.User.Email" />
                    <div class="item-form-container">
                        <label>Tipo Documento</label>
                        <select asp-items="@(new SelectList(Model.DocumentTypes,"Id","_DocumentType"))" asp-for="@Model.User.DocumentType_id" class="select">
                            <option value="" selected disabled>--Seleccione--</option>
                        </select>
                        <span asp-validation-for="@Model.User.DocumentType_id"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Nro de documento</label>
                        <input asp-for="@Model.User.DocumentNumber" value="@Model.User.DocumentNumber" />
                        <span asp-validation-for="@Model.User.DocumentNumber"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Nombre</label>
                        <input asp-for="@Model.User.Name" value="@Model.User.Name" />
                        <span asp-validation-for="@Model.User.Name"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Apellido</label>
                        <input asp-for="@Model.User.Surname" value="@Model.User.Surname" />
                        <span asp-validation-for="@Model.User.Surname"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Login</label>
                        <input asp-for="@Model.User.Login" value="@Model.User.Login" />
                        <span asp-validation-for="@Model.User.Login"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Password</label>
                        <input asp-for="@Model.User.Password" value="@Model.User.Password" type="password" />
                        <span asp-validation-for="@Model.User.Password"></span>
                    </div>
                    <div class="item-form-container">
                        <label>Perfil</label>
                        <select asp-items="@(new SelectList(Model.Profiles,"Id","_Profile"))" asp-for="@Model.User.Profile_Id" class="select">
                            <option value="" selected disabled>--Seleccione--</option>
                        </select>
                        <span asp-validation-for="@Model.User.Profile_Id"></span>
                    </div>
                    <div class="item-form-container check">
                        <input asp-for="@Model.User.Active" type="checkbox" checked="@Model.User.Active" style="width: 10%;" />
                        <label style="margin: 0;">Activo</label>
                    </div>
                </div>
                <div class="titulo-container"></div>
                <div class="button-container">
                    <div class="button-group-container">
                        <a href="/Users">
                            <div class="button"><span>Volver</span></div>
                        </a>
                        <input class="button" type="submit" value="Guardar" asp-page-handler="Update" />
                    </div>
                </div>
            </form>
        }
        @if (Model.Message != string.Empty)
        {
            <h2>@Model.Message</h2>
        }
    </div>
</body>
</html>

Adminsitrador.Usuarios.Web/Pages/Users/Index.cshtml
@page
@model Adminsitrador.Usuarios.Web.Pages.Users.IndexModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admi de Usuarios</title>
    <link href="~/css/users.css" rel="stylesheet" />
</head>
<body>
    <div class="page-container">
        <div class="titulo-container">
            <h3>Adminsitrador de usuarios</h3>
        </div>
        <div class="button-container">
            <div class="button-group-container">
                <a href="/Users/Action">
                    <div class="button"><span>Nuevo</span></div>
                </a>
            </div>
        </div>
        <div class="titulo-container subtitulo">
            <h3>Historial de usuarios</h3>
        </div>
        <div class="table-container">
            <div class="head">
                <div class="cell" style="width: 5%;"><span>Mod</span></div>
                <div class="cell" style="width: 3%;"><span>ID</span></div>
                <div class="cell" style="width: 15%;"><span>Tipo.Doc</span></div>
                <div class="cell" style="width: 12%;"><span>Nro.Doc</span></div>
                <div class="cell" style="width: 13%;"><span>Nombres</span></div>
                <div class="cell" style="width: 12%;"><span>Apellido</span></div>
                <div class="cell" style="width: 10%;"><span>Login</span></div>
                <div class="cell" style="width: 12%;"><span>Perfil</span></div>
                <div class="cell" style="width: 13%;"><span>Fecha creación</span></div>
                <div class="cell" style="width: 5%;"><span>Activo</span></div>
            </div>
            <div class="body">
                @{int i = 1; }
                @foreach (var item in @Model.Users)
                {
                    if ((i % 2) == 0)
                    {
                        <div class="item">
                            <div class="cell" style="width: 5%; justify-content: center;"><a href="@item.Mod"><div></div></a></div>
                            <div class="cell" style="width: 3%;"><span>@item.Id</span></div>
                            <div class="cell" style="width: 15%;"><span>@item.DocumentType</span></div>
                            <div class="cell" style="width: 12%;"><span>@item.DocumentNumber</span></div>
                            <div class="cell" style="width: 13%;"><span>@item.Names</span></div>
                            <div class="cell" style="width: 12%;"><span>@item.Surname</span></div>
                            <div class="cell" style="width: 10%;"><span>@item.Login</span></div>
                            <div class="cell" style="width: 12%;"><span>@item.Profile</span></div>
                            <div class="cell" style="width: 13%;"><span>@item.DateCreate</span></div>
                            <div class="cell" style="width: 5%;"><span>@item.Active</span></div>
                        </div>
                    }
                    else
                    {
                        <div class="item">
                            <div class="cell light" style="width: 5%; justify-content: center;"><a href="@item.Mod"><div></div></a></div>
                            <div class="cell light" style="width: 3%;"><span>@item.Id</span></div>
                            <div class="cell light" style="width: 15%;"><span>@item.DocumentType</span></div>
                            <div class="cell light" style="width: 12%;"><span>@item.DocumentNumber</span></div>
                            <div class="cell light" style="width: 13%;"><span>@item.Names</span></div>
                            <div class="cell light" style="width: 12%;"><span>@item.Surname</span></div>
                            <div class="cell light" style="width: 10%;"><span>@item.Login</span></div>
                            <div class="cell light" style="width: 12%;"><span>@item.Profile</span></div>
                            <div class="cell light" style="width: 13%;"><span>@item.DateCreate</span></div>
                            <div class="cell light" style="width: 5%;"><span>@item.Active</span></div>
                        </div>
                    }
                    i++;
                }
            </div>
        </div>
    </div>
</body>
</html>